parameters:
#    spot.example.class: Panelafrica\Bundle\SpotBundle\Example

services:
#    spot.example:
#        class: %spot.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
