parameters:
#    promo.example.class: Panelafrica\Bundle\PromoBundle\Example

services:
#    promo.example:
#        class: %promo.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
