parameters:
#    panel.example.class: Panelafrica\PanelBundle\Example

services:
#    panel.example:
#        class: %panel.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
