parameters:
#    news.example.class: Panelafrica\Bundle\NewsBundle\Example

services:
#    news.example:
#        class: %news.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
