parameters:
#    event.example.class: Panelafrica\Bundle\eventBundle\Example

services:
#    event.example:
#        class: %event.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
