parameters:
#    interview.example.class: Panelafrica\Bundle\InterviewBundle\Example

services:
#    interview.example:
#        class: %interview.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
