parameters:
#    questionnaire.example.class: Panelafrica\Bundle\QuestionnaireBundle\Example

services:
#    questionnaire.example:
#        class: %questionnaire.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
