parameters:
#    tombola.example.class: Panelafrica\Bundle\TombolaBundle\Example

services:
#    tombola.example:
#        class: %tombola.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
